Refactoring
TauZer0/QWT-Plot pull request #1
Opened 2020-02-20 14:45 UTC by TauZer0

2020-03-31 12:40 UTC, DimaTrushin requested changes
Я прошелся по коду. Очень неплохо. Направление правильное, написано здорово. Однако, есть некоторые промахи, по которым я прошелся в комментариях.

2020-03-31 12:40 UTC, DimaTrushin commented on functiontable.h
> +using FunctionSignature = double(double);
Убрать все using-и внутрь FunctionTable в приватную часть.

2020-03-31 12:40 UTC, DimaTrushin commented on functiontable.h
> +using std::map;
Никогда не открывай глобально имена из std. Если ты хочешь избавиться от написания std, то делай это локально. Например внутри класса, или внутри метода класса, или внутри функции. Но никогда НЕ делай это глобально.

2020-03-31 12:40 UTC, DimaTrushin commented on mainwindow.cpp
>      vbox = make_unique<QVBoxLayout>();
Тебе не надо руками создавать vbox здесь. Я понимаю, почему ты его добавил руками, потому что не получилось сделать в QtDesigner. Это известный баг дизайнера. Это делается так. Ты добавляешь в GroupBox любой элемент, например кнопку. После этого ты можешь применить к GroupBox вертикальный layout. После этого удаляешь кнопку из GroupBox и у тебя остается GroupBox с настроенным вертикальным layout.

Можно сделать еще лучше. Я напишу про это в письме с картинкой, тут это делать не удобно.

2020-03-31 12:40 UTC, DimaTrushin commented on plotter.cpp
> +void Plotter::set_legend() {
Так как легенду ты выводишь отдельно в объект vbox в виде списка галочек и имен функций, то может быть не стоит выводить эту легенду тут. Но это опциональное замечание. Можно его проигнорировать.

2020-03-31 12:40 UTC, DimaTrushin commented on plotter.h
> +using std::make_unique;
Убрать using-ги в приватную часть Plotter

2020-03-31 12:40 UTC, DimaTrushin commented on curvedata.h
> +    friend class Data;
Где тебе нужно, чтобы Data был другом CurveData???? Это плохо. Data является контейнером, который внутри себя содержит в том числе несколько CurveData. С какого перепуга он должен быть другом? Это ошибка дизайна. Друзьями могут быть итераторы контейнеров, или другие тесно связанные объекты. Члены класса не должны открывать хозяину себя. Это мусор. Представь, что ты CurveData будешь использовать без контейнера Data. У тебя любой другой контейнер Data может залезть в любую CurveData. Это может очень плохо закончиться.

В сухом остатке, убрать friend. И переделать так, чтобы это не понадобилось.

Я смотрю, что у тебя это нужно только в конструкторе Data, где ты руками вызываешь generate и обращаешься к X и Y в CurveData. Это ошибка дизайна. generate_X и generate_Y -- плохие функции. Во-первых, они выполняют только часть нужной задачи (например generate_X ломает инвариант класса, векторы X и Y не согласованы по длине), потому они могут быть только приватными. Во-вторых, generate_Y в качестве аргумента зачем-то получает информацию, которой он и так владеет -- массив X. В-третьих, это означает, что они должны быть частями метода generate, а сам метод generate должен вызываться в конструкторе CurveData. Это избавит тебя от необходимости вызова этих методов в конструкторе Data и не нужно делать friend.

2020-03-31 12:40 UTC, DimaTrushin commented on curvedata.h
> +    int alpha = 50;
Я не понял зачем нужен alpha. Плохое имя.

2020-03-31 12:40 UTC, DimaTrushin commented on curvedata.h
> +    int id = -1;
Я не понял роль id. Плохое имя.

2020-03-31 12:40 UTC, DimaTrushin commented on curvedata.h
> +    FunctionPtr function = nullptr;
Я не уверен, что хорошая идея по умолчанию в function пихать nullptr, это делает твой класс нерабочим. У тебя CurveData и так не является default constructible, потому тебе не надо ничего присваивать по умолчанию, тем более nullptr. Вместо этого в конструкторе проверь, что function после создания НЕ nullptr и поставь assert для проверки.

2020-03-31 12:40 UTC, DimaTrushin commented on curvedata.h
> +    void generate_X(double begin, double end, double step);
Эта функция должна быть private

2020-03-31 12:40 UTC, DimaTrushin commented on curvedata.h
> +    void generate_Y(const vector<double>& _X, FunctionPtr _function);
- Во-первых, эта функция должна быть private.
- Во-вторых, у этой функции не правильный интерфейс, должно быть
void generate_Y();
Она должна вызываться только после generate_X, потому она приватная. Она должна быть без аргументов, потому что класс и так знает про свой массив X и про свой указатель на функцию.

- В-третьих, надо добавить private(?) функцию
void generate(double begin, double end, double step);
Которая вызывает сначала generate_X, а потом generate_Y.

- В-четвертых, есть еще выбор, мы либо кидаем generate в конструктов CurveData, либо делаем ее открытой, но тогда она работает без каких либо проблем с friend-ами.

2020-03-31 12:40 UTC, DimaTrushin commented on data.cpp
> +    curves[0].generate_X(0, 5, 0.001);
- Во-первых, вот здесь по-хорошему должен быть просто вызов generate(0, 5, 0.001);
- Во-вторых, числа 0, 5, 0.001 являются магическими константами. То есть вместо этого лучше где-то иметь именованные константы.
- В-третьих, надо явно написать 0., 5., 0.001, чтобы было понятно, что это double литералы, а не int или unsigned int.

2020-03-31 12:40 UTC, DimaTrushin commented on data.h
> +    vector<CurveData> curves;
В классе Plotter у тебя находится два объекта класса FunctionPlot, а именно plot1 и plot2. Они явно согласованы с объектами из этого вектора. И тут видна ошибка дизайна. У тебя в Plotter-е поддержка рисования только двух графиков, а тут у тебя поддержка целого вектора, что плохо. Тут лучше сделать явно две кривые
CurveData curve1;
CurveData curve2;
Тем более, что ты везде явно работаешь с этими кривыми.

Кроме того, хранить в векторе кривые не очень хорошо, так как plot1 и plot2 ссылаются на адресса CurveData хранимых в векторе. Если ты его реаллоцируешь, то у тебя все посыпится. Эта проблема во многом решится с помощью Observer Pattern, но сейчас надо убрать вектор и сделать две отдельные кривые, иначе это ошибка проектирования.

2020-03-31 12:40 UTC, DimaTrushin commented on data.h
> +    const CurveData& get_curve(int i) const;
- Во-первых, тут вроде как ошибка в сигнатуре должно быть size_t вместо int, потому что ты обращаешься к элементам вектора.
- Во-вторых, после моего замечания про кривые, лучше тут иметь два метода
const CurveData& get_curve_1() const;
const CurveData& get_curve_2() const;

2020-03-31 12:40 UTC, DimaTrushin commented on functionplot.h
> +using std::make_unique;
Убрать глобальные using-ги внутрь класса.

2020-03-31 12:40 UTC, DimaTrushin commented on functionplot.h
> +    unique_ptr<QwtPlotCurve> curve;
Плохое название curve. Лучше сделать qwt_curve или что-то  в этом духе, ибо в классе CurveData тоже есть curve и теряешься, что есть что.

2020-03-31 12:40 UTC, DimaTrushin commented on functionplot.h
> +    QwtPlotCurve* get_curve() const {
Тут название тоже надо пересмотреть в соответствии с замечанием выше.

2020-03-31 12:40 UTC, DimaTrushin commented on mainwindow.h
>  private:
Во всех классах порядок следования данных такой:
1) Публичные методы.
2) Защищенные методы.
3) Приватные методы.
4) Приватные данные.
При этом в публичных методах сначала идут конструкторы.
Если требуется, то перед публичными методами можно в приватной или публичной части поставить необходимые using-ги.

Такой порядок связан с тем, что при дизайне систем (особенно графических или других, где производительность не главное) для тебя самое важное -- интерфейс класса. Его имплементация может поменяться миллион раз, а вот интерфейс -- это, как ты будешь использовать класс. И самое важное в интерфейсе -- конструкторы, то как ты будешь строить класс и какие инварианты он поддерживает.

Это изменение надо применить ко всем классам в коде.

2020-03-31 12:40 UTC, DimaTrushin commented on plotter.cpp
> +    auto curve = plot1.get_curve();
Очень опасная процедура -- сохранять ссылки. Ты тут просто хочешь передать ссылку на данные кривой в следующую функцию. Потому надо лишь написать в одну строчку
set_curve(plot1.get_curve(), curve_data);
и все.

2020-03-31 12:40 UTC, DimaTrushin commented on plotter.cpp
> +    curve->setRawSamples(curve_data.get_X().data(), curve_data.get_Y().data(), curve_data.get_X().size());
Когда ты видишь код типа
object.method()->function().attribute.call()->ptr;
Ты должен понимать, что это ошибка проектирования. В этом примере ты хочешь получить доступ к ptr, зная object и надо спуститься вниз до ptr через все вызовы подобъектов. Это означает, что ты дал слишком много информации. Ты должен был знать НЕ object, а всего лишь результат call(), для необходимого доступа, иначе ты знаешь слишком много.

В твоем случае curve_data должна напрямую предоставить метод data_X() вместо того, чтобы достучаться в X через get_X, а потом взять указатель.

Кроме того, тут есть еще одна глобальная проблема, связанная со смешиванием семантики. У тебя в языке программирования есть два типа объектов: by value и by reference. Первые объекты ты создаешь, копируешь, перемещаешь и так далее, это любые локальные переменные. Вторые объекты -- это те, которые ты создаешь по указателю и они лежат в одном и том же месте памяти. Так вот первые хороши тем, что они безопасны в использовании, но на них НЕЛЬЗЯ ссылаться, потому что мы не знаем, где в памяти они могут лежать в тот или иной момент. Вторые хороши тем, что на них можно ссылаться, они всегда лежат в одной и той же области памяти, но их нельзя копировать, мы не знаем как долго они живут и т.д. Так вот, у тебя curve_data хранится в векторе (после модификации как локальная переменная Data). Если вектор реаллоцирует, то все указатели внутри curve_data умрут. Эта проблема частично связана с тем, что тут надо использовать observe pattern и это сейчас моя задача, но про проблему я хотел написать, чтобы ты понимал.

В сухом остатке. Тут имеет смысл поправить интерфейс curve_data, чтобы были три метода: data_X(), data_Y() и data_size(). А вот бороться со второй проблемой буду я.

2020-03-31 12:40 UTC, DimaTrushin commented on plotter.h
> +    FunctionPlot plot1;
У тебя plot1 является участником Qt экосистемы. Он принимает сигналы от checkbox-а. Запомни, объекты Qt экосистемы обязаны лежать по одному адресу в памяти. Лучше их создавать как unique_ptr, а не локальными объектами на стэке. В данном случае у тебя Plotter создается по unique_ptr, потому его компоненты будут неподвижно лежать в памяти, но если ты потом что-то отрефакторишь, то это условие может нарушиться. Например, если ты захочешь вынести plot1 наружу из Plotter-а, то он может перестать быть ссылаемым объектом.

В сухом остатке, все участники Qt экосистемы должны быть либо указателями либо unique_ptr-ами. Указателями их делает Qt и сама парится с проблемами утечек памяти, а мы используем unique_ptr.

2020-03-31 12:40 UTC, DimaTrushin commented on plotter.cpp
> +    source->replot();
Я бы создал отдельный slot void replot() в самом Plotter, где вызывал бы этот метод, а тут бы вызвал бы этот слот. Зачем. У тебя plot1 и plot2 требуют вызывать source->replot(). Но сами plot1 и plot2 НЕ должны знать source. Вместо этого можно сделать так: plot1 и plot2 будут кидать сигналы Plotter-у о необходимости перерисовки. Тогда НЕ надо будет передавать source внутрь plot1 и plot2, о котором они знать не должны.

2020-03-31 12:40 UTC, DimaTrushin commented on plotter.h
> +// Ctrl+RighButton: zoom out to full size
Заметил баг. Когда делаешь ctrl+rightbutton или когда делаешь rightbutton до упора, то масштаб выходит НЕ на начальный, с которого ты стартовал, а на какой-то сильно больше 500 на 1000 из-за чего не видно стартовых графиков. Так быть не должно. Надо чтобы тебя откидывало в то состояние, с которого ты начинал, а не в абстрактное дефолтное.

2020-03-31 12:40 UTC, DimaTrushin commented on zoomer.cpp
> +    background.setAlpha(200);
Магическая константа 200!
НИКОГДА НЕ ДОЛЖНО БЫТЬ МАГИЧЕСКИХ КОНСТАНТ!
Я готов еще раз 20 напечатать этот текст руками без зажатия капслока и без копипасты только для того, чтобы эта мысль отложилась как можно глубже в голове. Я написал замечание здесь, но его надо применить КО ВСЕМ магическим константам в коде.

Как бороться с магическими константами. Смотри, раз тебе нужна эта константа только внутри класса Zoomer, то ты можешь сделать приватную constexpr статическую константу внутри Zoomer объясняющую, что это за константа. Например, внутри class Zoomer
private:
static constexpr const int k_default_background_alpha = 200;
снабжаем константную переменную префиксом k_ чтобы было понятно, что это константа.

2020-03-31 12:40 UTC, DimaTrushin commented on mainwindow.h
> +    unique_ptr<Plotter> plotter;
Забыл написать сразу. Все приватные и защищенные данные класса должны иметь постфикс _. Аименно plotter_ вместо plotter и т.д. Это нужно для того, чтобы внутри методов класса видеть, какие переменные являются членами класса и отличать их от локальных переменных методов. Это важно, потому что члены класса являются для методов класса глобальными перменными. И их не найти в определении метода и на их значение может повлиять любой метод. Потому нужно, чтобы визуально их было легко отслеживать.

Это замечание надо применить КО ВСЕМ классам.

2020-03-31 12:40 UTC, DimaTrushin commented on zoomer.cpp
> +QwtText Zoomer::trackerTextF(const QPointF& pos) const {
Старайся избегать сокращений. Имя pos не сильно короче position, но менее читаемо.

2020-03-31 12:40 UTC, DimaTrushin commented on zoomer.h
> +    Zoomer(QWidget* _canvas);
Если использовать для переменных класса underscore в конце, это избавит от подобных проблем с именами в конструкторе. Например у тебя
canvas_
будет локальной переменной, тогда в конструкторе ты пишешь
Zoomer(QWidget* canvas) : canvas_(canvas) {...}
У тебя пропадает необходимость придумывать дурацкие названия для аргументов.

Кроме того, в плюсах имена начинающиеся с underscore часто зарезервированы. Внутри класса и функций можно использовать _d... то есть underscore и потом маленькую букву, но нельзя использовать _D... underscore и заглавную букву. Кроме того, никогда нельзя использовать двойной underscore независимо от положения в имени ss__d Потому underscore используют только после имен или внутри и только одинарный.

2020-03-31 12:40 UTC, DimaTrushin commented on functionplot.cpp
> +    source->replot();
Вместо вызова source->replot() кидай сигнал emit plot_changed();
Далее соедени этот сигнал со слотом replot в Plotter, про который я писал.
В итоге тебе НЕ надо будет хранить указатель на source внтури plot1 и plot2.

2020-03-31 12:40 UTC, DimaTrushin commented on plotter.h
> +    QVBoxLayout* vbox; // Borrow
Тебе НЕ надо хранить этот указатель в Plotter, ты его используешь лишь для того, чтобы передать их в конструкторы plot1 и plot2.

2020-03-31 12:40 UTC, DimaTrushin commented on functionplot.h
> +    QwtPlot* source; // Borrow
Если кидать сигнал, то source не нужен.

2020-04-01 13:35 UTC, TauZer0 commented on curvedata.h
> +    int alpha = 50;
Имелась в виду прозрачность заливки интервалов. Переименовал в opacity.

2020-04-01 13:36 UTC, TauZer0 commented on curvedata.h
> +    int id = -1;
Удалил поле id, оно пока нигде не используется.

2020-04-01 19:29 UTC, DimaTrushin commented on curvedata.h
> +    int alpha = 50;
Тогда надо interval_opacity например. И еще я вижу, что тебе лучше использовать одну структуру данных для чисто кривых и другую для кривых с интервалами. Например вторую можно унаследовать от первой, чтобы не было дублирования кода.

2020-04-14 18:06 UTC, TauZer0 commented
> Вот так делать нельзя. У тебя при каждом вызове set_function1 будет создаваться еще одно соединение. И в итоге для каждого соединения будет вызван replot. Соединение -- это часть твоей структуры, а не рутина, которую ты выполняешь раз за разом. Задача set_function1 лишь в том, чтобы поменять данные в первом графике, эта функция НЕ должна менять взаимоотношение plotter-а с его графиками.
> Чтобы избежать таких ошибок, думай над ситуацией, когда ты функцию вызываешь несколько раз из случайных мест, где доступен plotter. Сразу станет понятно, что она должна делать, а что нет.
> 
> Перенести все connect внутрь конструктора Plotter.

Поправил.

2020-04-14 18:07 UTC, TauZer0 commented
> Еще одна ошибка дизайна.
> Ты с помощью функций
> set_main_curve
> set_curve
> настраиваешь объекты plot1_ и plot2_, а потом руками вызываешь replot в Plotter. Должно быть не так. Plotter должен отвечать за свою структуру, а FunctionPlot plot1_ и plot2_ должны сами отвечать за свою структуру. Если плоттер хочет изменить что-то в своих переменных plot1_ и plot2_, то он должен у них вызвать нужный метод.
> 
> Как я вижу правильный подход. У тебя FunctionPlot должен иметь метод (название первое приходящее в голову)
> set_function_data
> Этот метод выполняет то, что делает set_main_curve (кстати, дурацкое ни о чем не говорящее название) и потом set_function_data сам кидает сигнал о том, что данные изменились. И потому после ее вызова НЕ надо вызывать replot. Он вызовется по сигналу, который ты уже соединил в конструкторе.

Поправил.

2020-04-18 11:04 UTC, TauZer0 commented on functiontable.h
> +using std::map;
Перенести внутрь класса не получилось, не компилируется. Решил убрать using-и совсем и писать через std::.

2020-04-18 11:13 UTC, TauZer0 commented on functiontable.h
> +using FunctionSignature = double(double);
Тут возникает проблема, что приходится писать конструкции типа `FunctionTable::FunctionPtr FunctionTable::operator[](const FunctionTable::FunctionName& name)`. А в других классах использовать эти имена уже нельзя.

2020-06-19 03:12 UTC, merged